version: '3'

services:

    jenkins:
        image: jenkins/jenkins:lts-alpine
        ports:
            - 8080:8080
            - 50000:50000
        volumes:
            - ./vols-rw/jenkins_home:/var/jenkins_home
            - ./vols-rw/var/lib/docker:/var/lib/docker

    node-ubuntu:
        build:
            context: ./services/jenkins-node-ubuntu
            dockerfile: Dockerfile
        volumes:
            - ./vols-rw/workspace:/workspace
            - ./vols-rw/var/run:/var/run
        depends_on:
            - jenkins
            - dind

    dind:
        image: docker:18.04.0-ce-dind
        privileged: true
        volumes:
            - ./vols-rw/workspace:/workspace
            - ./vols-rw/var/run:/var/run

