version: '3.4'

services:

    jenkins:
        image: jenkins/jenkins:lts-alpine
        ports:
            - 8080:8080
            - 50000:50000
        volumes:
            - ./vols-rw/jenkins_home:/var/jenkins_home
            - ./vols-rw/var/lib/docker:/var/lib/docker

    dind:
        image: docker:18.04.0-ce-dind
        privileged: true
        volumes:
            - ./vols-rw/workspace:/workspace
            - ./vols-rw/var/run:/var/run

    gitlab:
        image: gitlab/gitlab-ce:latest
        ports:
            - "9443:443"
            - "9080:80"
            - "9022:22"
        volumes:
            - ./vols-rw/gitlab/config:/etc/gitlab
            - ./vols-rw/gitlab/logs:/var/log/gitlab
            - ./vols-rw/gitlab/data:/var/opt/gitlab

  
